"""empty message

Revision ID: 22223fff79f8
Revises: d2ac9438bce2
Create Date: 2022-12-11 19:54:24.567129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22223fff79f8'
down_revision = 'd2ac9438bce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_in')
    # ### end Alembic commands ###
