"""empty message

Revision ID: 313fd793f3c1
Revises: 4f91cfaaeb9c
Create Date: 2023-01-08 14:46:07.293738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313fd793f3c1'
down_revision = '4f91cfaaeb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'status')
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    op.add_column('rental', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
