"""empty message

Revision ID: f7a42090e767
Revises: 7cdab2d4835a
Create Date: 2022-12-10 20:56:02.228723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a42090e767'
down_revision = '7cdab2d4835a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    # ### end Alembic commands ###
